apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-generator.fullname" . }}
  labels:
    {{- include "exchange-generator.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: {{ .Values.SPRING_APPLICATION_NAME }}

  KEYCLOAK_ISSUER_URI: {{ .Values.KEYCLOAK_ISSUER_URI }}

  LOG_LEVEL: {{ .Values.LOG_LEVEL }}

  SERVICE_URL_EXCHANGE: {{ .Values.SERVICE_URL_EXCHANGE }}

  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.KAFKA_BOOTSTRAP_SERVERS }}
  KAFKA_EXCHANGE_RATES_TOPIC: {{ .Values.KAFKA_EXCHANGE_RATES_TOPIC }}

immutable: true