apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker.fullname" . }}
  labels:
    {{- include "blocker.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8080"

  SPRING_APPLICATION_NAME: {{ .Values.SPRING_APPLICATION_NAME }}

  KEYCLOAK_ISSUER_URI: {{ .Values.KEYCLOAK_ISSUER_URI }}

  LOG_LEVEL: {{ .Values.LOG_LEVEL }}

  CONFIRM_PROBABILITY: {{ .Values.CONFIRM_PROBABILITY | quote }}

immutable: true