apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front.fullname" . }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: {{ .Values.SPRING_APPLICATION_NAME }}

  KEYCLOAK_ISSUER_URI: {{ .Values.KEYCLOAK_ISSUER_URI }}

  LOG_LEVEL: {{ .Values.LOG_LEVEL }}

  SERVICE_URL_ACCOUNT: {{ .Values.SERVICE_URL_ACCOUNT }}
  SERVICE_URL_CASH: {{ .Values.SERVICE_URL_CASH }}
  SERVICE_URL_TRANSFER: {{ .Values.SERVICE_URL_TRANSFER }}
  SERVICE_URL_EXCHANGE: {{ .Values.SERVICE_URL_EXCHANGE }}
  SERVICE_URL_FRONT: {{ .Release.Namespace }}.{{ .Values.HOST_NAME }}

immutable: true