apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "front.fullname" . }}-ingress
spec:
  rules:
  - host: {{ .Release.Namespace }}.{{ .Values.HOST_NAME }}
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: {{ include "front.fullname" . }}
              port:
                number: 8080