apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "account.fullname" . }}-db
spec:
  serviceName: {{ include "account.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "account.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "account.fullname" . }}-db
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          env:
            - name: POSTGRES_DB
              value: data
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "account.fullname" . }}
                  key: DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  {{ include "account.fullname" . }}
                  key: DATASOURCE_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgres/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "account.fullname" . }}-db
spec:
  clusterIP: None
  selector:
    app: {{ include "account.fullname" . }}-db
  ports:
    - name: 5432-5432
      port: 5432
      targetPort: 5432
      protocol: TCP