apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cash.fullname" . }}
  labels:
    {{- include "cash.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: {{ .Values.SPRING_APPLICATION_NAME }}

  DATASOURCE_URL: jdbc:postgresql://{{ include "cash.fullname" . }}-db:5432/data
  KEYCLOAK_ISSUER_URI: {{ .Values.KEYCLOAK_ISSUER_URI }}

  LOG_LEVEL: {{ .Values.LOG_LEVEL }}

  SERVICE_URL_ACCOUNT: {{ .Values.SERVICE_URL_ACCOUNT }}
  SERVICE_URL_BLOCKER: {{ .Values.SERVICE_URL_BLOCKER }}
  SERVICE_URL_CASH: {{ .Values.SERVICE_URL_CASH }}

  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.KAFKA_BOOTSTRAP_SERVERS }}
  KAFKA_NOTIFICATIONS_TOPIC: {{ .Values.KAFKA_NOTIFICATIONS_TOPIC }}

immutable: true
